version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.7

    steps:
      - checkout

      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies
          command: yarn --pure-lockfile
      - save_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Install bower dependencies
          command: |
            npm i bower
            ./node_modules/bower/bin/bower i
      - save_cache:
          key: bower-deps-{{ checksum "bower.json" }}
          paths:
            - ./bower_components

  test:
    docker:
      - image: circleci/node:8.7-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Test
          command: ./node_modules/ember-cli/bin/ember test

  deploy:
    docker:
      - image: circleci/node:8.7
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Deploy to GitHub Pages
          command: |
            git checkout gh-pages; git checkout master
            ./node_modules/ember-cli/bin/ember deploy production

workflows:
  version: 2
  install-test-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]\.[0-9]\.[0-9]+/
            branches:
              only: demo
